---
language: python
python: "2.7"
env:
  - ANSIBLE_VERSION: "latest"

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
